timeout: 800 # Number of days of inactivity that is allowed

testing:
  #user that will get the test notification
  # Find user in slack sidebar -> View full profile
  user_msg: U03SNA4F0 # nikolas
  user_test: U02KRH15ZBK # Nikolas (slettmeg)

channels:
  testing: test-vaskehjelp
  logging: logging-vaskehjelp
  adding:
    - alumni
  cleanup:
    - bar
    - kafé
    - arrangement
    - promotering
    - dj
    - utlån
    - økonomi


# Testes med poetry
message: |
  Hi! 
  We are currenly doing some automated cleaning of the work groups. 
  The groups (like Kafe, Bar etc) is intended for active communication,
  we have therefore removed inactive members and added them to the alumnus channel.
  
  If you feel a mistake has been made, please rejoin the channels in question :)
